---
 - hosts: managed_servers
   gather_facts: true
   become: true
   tasks:
   
    - name: Test for Proxmox
      stat:
        path: /etc/pve
      register: is_proxmox

    - name: Fail if not Debian
      fail:
        msg: This Playbook is not intended for {{ hostvars[inventory_hostname].TYPE }} hosts
      when:  not hostvars[inventory_hostname].TYPE == "debian"

    - name: Fail if already Proxmox host
      fail:
        msg: This Playbook is intended for Debian 12 hosts without proxmox only.  
      when: is_proxmox.stat.exists

    - name: Add the Proxmox VE repository
      lineinfile:
        path: /etc/apt/sources.list.d/pve-install-repo.list
        line: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
        create: yes
    
    - name: Add the Proxmox VE repository key as root
      ansible.builtin.get_url:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg 
        dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
        mode: '0644'
    
    - name: Update your repository and system
      become: true
      apt:
        upgrade: full
        update_cache: yes
    
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
    
    - name: Install the Proxmox VE packages
      ansible.builtin.apt:
        name: 
          - proxmox-ve
          - postfix
          - open-iscsi
          - chrony
        state: latest
    
    - name: Remove the Debian Kernel
      ansible.builtin.apt:
        name: 
          - linux-image-amd64
          - 'linux-image-6.1*'
        state: absent
    
    - name: update-grub
      shell: update-grub
    
    - name: Remove the Debian Kernel
      ansible.builtin.apt:
        name:
          - os-prober
        state: absent
    
    - name: Fix enterprise repo to remove enterprise sub
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: '^deb'
        replace: '#deb'
    
    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
    
