---
- hosts: managed_servers
  gather_facts: true
  become: true
  tasks:
  - name: Test for Proxmox
    stat:
      path: /etc/pve
    register: is_proxmox
  - name: Fail if already Proxmox host
    fail:
      msg: This Playbook is intended for Proxmox hosts only.  
    when: not is_proxmox.stat.exists
